#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""

import sys

def factorize(value):
    """ print a simple array of numbers."""
    factors = []
    for i in range(2, value // 2 + 1):
        if value % i == 0:
            factors.append((i, value // i))
    return factors

def main(file_path):
    try:
        with open(file_path, "r") as file:
            for line in file:
                value = int(line.strip())
                read_line = factorize(value)
                for n in read_line:
                    p, q = n
                    print(f"{value}={p}*{q}")
    except FileNotFoundError:
        print(f"Error: File not found: {file_path}")
    except ValueError:
        print("Error: Invalid number of file.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)
